choco install choco-protocol-support -y --ignore-checksums
choco install googlechrome -y --ignore-checksums
choco install 7zip -y --ignore-checksums
choco install vcredist-all -y --ignore-checksums
choco install directx -y --ignore-checksums
choco install dotnetfx -y --ignore-checksums
choco install dotnet3.5 -y --ignore-checksums
choco install dotnet4.5.2 -y --ignore-checksums
choco install k-litecodecpackmega -y --ignore-checksums
choco install imageresizerapp -y --ignore-checksums
choco install flameshot -y --ignore-checksums
